---
title: "Compiled Dictionary"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---
We have the folowing datasets:

RapidProgression.csv
  multiple radiographs from multiple years per miner
  final PMF stage from final radiograph per miner
  final CWP stage from final radiograph per miner
  underground mining tenure
  coalface mining tenure
  age of miner at final radiograph
  mine size 
  geographic region
  
ncsr1.csv
  one radiograph per miner
  age at time of radiograph
  presence of CWP 1/0 or greater (less than or postive)
  presence of CWP 2/1 or greater (less than or postive)
  region (by coal type)
  exposure (gram-hours per cubic meter)
  
Kentucky_Virginia.csv
  multiple radiographs per miner
  year of xray
  final PMF stage
  final CWP category 
  underground tenure 
  coal face indicator (yes/no) at last xray
  bolt driller indicator (yes/no) at last xray
  driller tenure group
  
CaseStudy.csv
  multiple radiographs per miner
  year of xray
  age group of miner 
  pmf stage 
  SPO profusion category
  yes or no coalescense 
  total mining tenure group 
  coal face tenure 

ncsr4.csv
  Age:    Age at time of medical survey (years)
  Cat1:   Indicator showing presence or absence of category 1/0 or greater
  Cat2:   Indicator showing presence or absence of category 2/1 or greater
  PMF:    Indicator showing presence or absence of progressive massive fibrosis
  Region: coal rank region
  Exp:    Respirable dust exposure (gram-hours per cubic meter)               

